apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-nginx
  template:
    metadata:
      labels:
        app: php-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
        - name: php
          image: php:fpm-alpine
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
      volumes:
        - name: app-code
          configMap:
            name: php-app-code
        - name: nginx-conf
          configMap:
            name: nginx-config